### ISSUE TITLE
customize Radio button

### ISSUE THREAD

**Issue by rohanrajpal** [kgnugur/formik-chakra-ui#1]
Hey, I want to use the following example of Radio buttons with formik
https://chakra-ui.com/docs/form/radio#custom-radio-buttons

I understand that I would need to use hooks to achieve this, but should the `group` property go into `RadioControlGroup`?

A followup question, my form has 4 radio buttons; that's a lot of hooks for a single page. Is there any other way to use custom radio buttons? I'm new to react and am not completely sure how to go about this

**Comment by kgnugur** [comment]
Hi,
Sorry for the late response, happy new year.

Well, you want a custom radio button. Formik-chakra-ui is for common and repetitive use cases. For the rest edge cases, chakra-ui is really good. If you want to use the default radio box, just plug and play it from Formik-chakra-ui (If you need to customize props, then you can. [Here are typings from docs](https://angry-einstein-b7909a.netlify.app/docs/api/formik-ui/#radiogroup)).

As for your follow-up question, you can create two custom components one for `Radio --> RadioCard (as shown in docs)`  and one for `RadioGroup` using `useRadioGroup`. I can create an example for you tomorrow if you need one.

**Comment by rohanrajpal** [comment]
> Hi,
> Sorry for the late response, happy new year.
> 
> Well, you want a custom radio button. Formik-chakra-ui is for common and repetitive use cases. For the rest edge cases, chakra-ui is really good. If you want to use the default radio box, just plug and play it from Formik-chakra-ui (If you need to customize props, then you can. [Here are typings from docs](https://angry-einstein-b7909a.netlify.app/docs/api/formik-ui/#radiogroup)).
> 
> As for your follow-up question, you can create two custom components one for `Radio --> RadioCard (as shown in docs)` and one for `RadioGroup` using `useRadioGroup`. I can create an example for you tomorrow if you need one.

Hey Kağan

Yeah, currently I'm using your library and it helped me a lot. Yeah I think making a custom RadioGroup should do the trick, I'll try it out.

**Comment by rohanrajpal** [comment]
Hey @kgnugur 

I was trying to make a custom radio group component but came across the following problem.

Before using a RadioCard I have to `const radio = getRadioProps({ value })`, but the getRadioProps function is defined in my `RadioGroup` custom component.

Do you know how to can get functions from parent and pass them to the child? We do something similar in Formik like 'handlechange` and call them in the child

I basically want to do something like this
```tsx
<CustomRadioGroup>
  {({ getRadioProps }) => (
    {options.map((value) => {
            const radio = getRadioProps({ value })
            return (
              <RadioCard key={value} {...radio}>
                {value}
              </RadioCard>
            )
          })}
    )}
</CustomRadioGroup>

**Comment by dbousamra** [comment]
https://codesandbox.io/s/gallant-shannon-3urpz?file=/src/index.tsx

An example sandbox with a custom radio group component hooked up via Formik
