### ISSUE TITLE
Remove default marginY value?

### ISSUE THREAD

**Issue by bjoluc** [kgnugur/formik-chakra-ui#10]
Hi @kgnugur and thanks for making my life a bit easier with this lib :smile: 
I decided to open a new issue on this to continue the discussion from #9. I would like the my={4} setting to be removed as well, since it eases the transition from plain Chakra UI components and users can still pass it if they want to. One might argue that a user may also pass `my={0}` to every component (which is what I do right now), but generally, I think, it is better practice to use a Grid with `rowGap={8}` for this kind of styling. My opinion though, and your opinionated lib :wink:

**Comment by kgnugur** [comment]
Hey thank you,

I will release a new version, with margins removed as I agree with points. 😜

**Comment by bjoluc** [comment]
Neat, thanks in advance! :rocket:

**Comment by kgnugur** [comment]
You can take a look at '1.4.4' 🎉
