### ISSUE TITLE
May I ask how to show the password for the InputControl?

### ISSUE THREAD

**Issue by zhiwehu** [kgnugur/formik-chakra-ui#103]

**Comment by vxxvvxxv** [comment]
+1

**Comment by aircliff** [comment]
Same issue +1

**Comment by aircliff** [comment]
Actually I figured out the solution, the input elements props can be passed via `inputProps`. So the password input field would look something like this:

```tsx
<InputControl name="password" inputProps={{ type: "password" }} label="Password" />
```

I think including that input props can be passed via `inputProps` in the docs would be very helpful.

**Comment by shadesOfcodes** [comment]
also being able to pass left and right icons

**Comment by kgnugur** [comment]
Thank you for the issue. I've just updated to example sandbox.
