### ISSUE TITLE
Support for FormHelperText

### ISSUE THREAD

**Issue by bjoluc** [kgnugur/formik-chakra-ui#11]
And here it is, another ["Someone approaches you with a new use case that your code doesn't quite support, but could with a little tweak."](https://kentcdodds.com/blog/inversion-of-control) step. Do whatever you want with the suggestion :stuck_out_tongue_winking_eye:

As the title says, I'd welcome support for [`FormHelperText`](https://chakra-ui.com/docs/form/form-control#usage). Happy to do a PR if you want. I'd implement it by adding a `helperText` prop to your `FormControl` component. Looking forward to your feedback :)

**Comment by kgnugur** [comment]
Well, it is a nice request :). PR's are always welcome but I will add it soon.

**Comment by bjoluc** [comment]
Hi, glad to hear you're up to this anyway! I'll happily leave it to you then :sweat_smile:

**Comment by kgnugur** [comment]
1.4.5 is published 🎉.
`helperText?: string;` Prop is added. 🙂

**Comment by bjoluc** [comment]
Beautiful, thanks! :relaxed:
