### ISSUE TITLE
Type Of input element not working

### ISSUE THREAD

**Issue by anshuopinion** [kgnugur/formik-chakra-ui#3]
![image](https://user-images.githubusercontent.com/50476777/103722138-52d1e000-4ff5-11eb-8370-ff6b194ff922.png)

**Comment by anshuopinion** [comment]
![Uploading image.png…]()

**Comment by anshuopinion** [comment]
![issueFormik](https://user-images.githubusercontent.com/50476777/103725175-00e08880-4ffc-11eb-95ea-bbdda7ada412.png)

kindly add type property

**Comment by kgnugur** [comment]
Hi, as you can [see from the documentation](https://angry-einstein-b7909a.netlify.app/docs/api/formik-ui/#inputcontrol) if you need to pass any FormControl Props than you can pass it directly. If you need to pass props of inner component `Input` in this case then pass it via `inputProps` property.
So, what you need is:
`<InputControl name="firstName" label="First Name" inputProps={{type: "email"}}  />
`

**Comment by anshuopinion** [comment]
thanks for help bro
