### ISSUE TITLE
Radio Control Buttons does not show validation error

### ISSUE THREAD

**Issue by zhenming91** [kgnugur/formik-chakra-ui#4]
![image](https://user-images.githubusercontent.com/42268066/103814939-e097e480-5062-11eb-8899-73559b7508e6.png)

Back with another issue, this time I noticed that the error message from validation does not appear after clicking submit.

**Comment by kgnugur** [comment]
Hi,
[Here](https://codesandbox.io/s/formik-chakra-ui-forked-gdvw0?file=/src/Form.tsx), added `.required()` and `oneOf(["#ff0000"])`. `formik-chakra-ui' seems to pick up the error message correctly.
![image](https://user-images.githubusercontent.com/28161197/103865925-f85c8080-50d5-11eb-9a8c-559da1fedb84.png)
