### ISSUE TITLE
No longer able to select by label text with React Testing library

### ISSUE THREAD

**Issue by PedroDBFlores** [kgnugur/formik-chakra-ui#6]
Hello.

Steps to reproduce:

1. Have formik-chakra-ui at version 1.4.1
2. Clone my minimum example repo from https://github.com/PedroDBFlores/chakra-ui-formik-problem
3. Run the tests with the current 1.4.1 version

Expected result:
Both tests should pass

Actual result:
I'm no longer able to get the selector by using the label which is labeling it.

I've checked the recent commits, might the `id` removal from the **SelectControl** have something to do with it? This might also break accessiblity by not being able to use aria-label on the select label.

**Comment by kgnugur** [comment]
Hi,
Thank you for the detailed issue. It's probably because of `id` like you said. I will look into that.

**Comment by kgnugur** [comment]
I probably need to write tests, but for now, I used Kent's `Testing Playground` and it looks like it is working. Some other components had the same issue too. Fixed in https://github.com/kgnugur/formik-chakra-ui/commit/253ae62388cab9d7c705c1d6bf45a565ac8a9451
You can try `1.4.2`

Thanks a lot!

**Comment by PedroDBFlores** [comment]
It now works again, thanks your your availability to promptly fix it 👍
