### ISSUE TITLE
Not possible to pass a specific type (eg: "password")  in the ```InputControl```.

### ISSUE THREAD

**Issue by Charlesdoiron** [kgnugur/formik-chakra-ui#73]
Hello,
thanks a lot for this lib !
I'm trying it and i cant add a _password type_ for the `inputControl`.
Like this : 

` <InputControl type="password" name="password" label="password" />`

There is a Typescript error : 

`Property 'type' does not exist on type 'IntrinsicAttributes & BaseProps & { inputProps?: InputProps | undefined; } & { children?: ReactNode; }'`

It's possible to do it on Chakra :

`function PasswordInput() {
  const [show, setShow] = React.useState(false)
  const handleClick = () => setShow(!show)

  return (
    <InputGroup size="md">
      <Input
        pr="4.5rem"
        type={show ? "text" : "password"}
        placeholder="Enter password"
      />
      <InputRightElement width="4.5rem">
        <Button h="1.75rem" size="sm" onClick={handleClick}>
          {show ? "Hide" : "Show"}
        </Button>
      </InputRightElement>
    </InputGroup>
  )
}`

Thanks a lot !

**Comment by dimitriharding** [comment]
Any update on a fix for this issue?

**Comment by suparjitoteo** [comment]
@Charlesdoiron @dimitriharding 

You need to put the type inside the inputProps.
`<InputControl
              name="password"
              label="Password"
              inputProps={{
                type: "password",
              }}
            />`


if you see the code in the package, you can see that InputControl receive this props.
`export type InputControlProps = BaseProps & { inputProps?: InputProps };`

That BaseProps is basically FormControlProps from chakra.
