### ISSUE TITLE
Why Input Control is wrapped with formcontrol , due that i am not able use inputLeftElement

### ISSUE THREAD

**Issue by anshuopinion** [kgnugur/formik-chakra-ui#8]
![image](https://user-images.githubusercontent.com/50476777/108950699-a3c49300-768c-11eb-9892-c836410e1688.png)

**Comment by kgnugur** [comment]
What you are doing here is composing different components together. Now, this library's purpose is to give you some easily usable tightly coupled components. `FormControl` is responsible for things like `isInvalid, isDisabled, isRequired`. Now I can just give you an API something like `notUseFormControl: boolean`. But this time you need to manage to put the `FormControl` to the right place the right way.
 You may as well create a custom component and use it if you want. Without messing with `formik-chakra-ui`.
 
That said I'm open to suggestions for new components or API change.
Thanks.

**Comment by anshuopinion** [comment]
thanks, bro For the help Your Package is awesome.

I used the following code to resolve issue.


`  <Field name="mobile">
                                    {({ field }) => (
                                        <InputGroup mb={4}>
                                            <InputLeftElement
                                                pointerEvents="none"
                                                children={
                                                    <Icon color="main.m">
                                                        <FontAwesomeIcon
                                                            icon={faPhone}
                                                        />
                                                    </Icon>
                                                }
                                            />
                                            <Input
                                                {...field}
                                                type="tel"
                                                placeholder="Mobile Number"
                                                focusBorderColor="main.d"
                                            />
                                        </InputGroup>
                                    )}
                                </Field>`
