### ISSUE TITLE
facing problem while changing font size of Inputcontrol

### ISSUE THREAD

**Issue by anshuopinion** [kgnugur/formik-chakra-ui#84]
![image](https://user-images.githubusercontent.com/50476777/139013048-be395098-a616-4d50-b426-f0fc5e74e052.png)

by default label using this fontSize I am not able to change this.

**Comment by kgnugur** [comment]
Hi,

This is related to https://github.com/kgnugur/formik-chakra-ui/issues/91#issuecomment-986073187 .
`FormControl` does not accept things like `FormLabel`, `FormErrorMessage`, and `FormHelperText`.

Will do an update after taking contributors opinions.

**Comment by kgnugur** [comment]
You can use `labelProps` with version `1.60.`
