### ISSUE TITLE
Placeholder not working while doing TextAreaControl and InputControl

### ISSUE THREAD

**Issue by Sparklytical** [kgnugur/formik-chakra-ui#9]
For example while doing this - 
```js
 <TextareaControl
    name="text"
    placeholder="Add your comment..."
    bg={bg}
    pt={0}
    mt={0}
    isDisabled={!data?.Me.user}
    />
```

The placeholder isn't visible or even present in there while checking with inspect tools.

Formik - 2.2.6
Chakra UI - 1.3.3
formik-chakra-ui - 1.4.3

ps - thanks for this library, it saves much time and complexity

**Comment by kgnugur** [comment]
Hey,
I will look in to that tomorrow, thanks for reporting the issue man.

**Comment by kgnugur** [comment]
Hi,
The thing is `FormControl` accepts `placeholder` but it does nothing with it. It's weird so I opened an issue on `chakra-ui`.
https://github.com/chakra-ui/chakra-ui/issues/3502

So if you use it like this:
```
            <TextareaControl
              name="notes"
              label="Notes"
              textareaProps={{ placeholder: 'hello' }}
            />
```
It will work. I'm not sure if I should change the API and directly bind the placeholder like you wanted to use. It may be convenient for people.

**Comment by Sparklytical** [comment]
It's working now, and the reason Segun gave is also acceptable.

Also one question, will it be better to remove the custom paddings/margins that you have given to the inputs because I've to remove the margins / padding by setting them to 0 while using them.

**Comment by kgnugur** [comment]
Sorry for the late reply, been busy.

I thought about what you said while writing the lib. The margins are mostly for convenience. But it can be cumbersome for some people. I thought about something like the config. That you can put it at the root of your project and be fine with it.
Something like:

```
  <FormikChakraUI mY={0}>
    <App />
  <FormikChakraUI>
```

**Comment by Sparklytical** [comment]
I think this is rather easy way to do that but some people might not like adding another context in their app.

But then again if you think about it, the margin you think is perfect for you, for me might not fit on others and again they will have to change it. So I think it's better to just remove them and people can handle it themselves.

**Comment by kgnugur** [comment]
@Sparklytical 
Hey, I removed the margins as I agree with your points.
Will close the issue, since https://github.com/kgnugur/formik-chakra-ui/issues/10 is opened.
Thanks.

**Comment by watnFoehn** [comment]
For everyone who is coming later and is wondering why this doesn't work for InputControl:
           ```
 <TextareaControl
              name="notes"
              label="Notes"
              textareaProps={{ placeholder: 'hello' }}
            />
```

It has to be passed like this:
`<InputControl
                    name="test"
                    inputProps={{ placeholder: "hello" }}
                  />`
