### ISSUE TITLE
Export the base form control component

### ISSUE THREAD

**Issue by wkrasnicki** [kgnugur/formik-chakra-ui#91]
I know this library is for Chakra UI only, but I would like to use other input types as well. For example I would like to extend this library to support [@choc-ui/chakra-autocomplete](https://www.npmjs.com/package/@choc-ui/chakra-autocomplete) and it would be easier if I had access to `BaseProps` and modified `FormControl`.

**Comment by verekia** [comment]
Also, if either PR for exporting `FormControl` gets merged, I'll make an other PR to make it possible to pass props to `FormLabel`, `FormErrorMessage`, and `FormHelperText` as well.

**Comment by kgnugur** [comment]
I accepted the PR that exports `FormControl`.  

I'm thinking of adding `FormLabel`, `FormErrorMessage`, and `FormHelperText`  to `BaseProps` but it can complicate things in a bad way.

What is your preferred way to go here? @verekia @wkrasnicki , opinions are very applicated.

Thank you and sorry for the delay.

**Comment by wkrasnicki** [comment]
How bad would adding these props complicate things? Wouldn't passing them as nested objects (like inputProps etc) be sufficient?

**Comment by verekia** [comment]
I made a PR. What do you guys think of #102?

> I'm thinking of adding `FormLabel`, `FormErrorMessage`, and `FormHelperText` to BaseProps but it can complicate things in a bad way.

I'm not sure if my PR is what you meant. Did you have something else in mind?

**Comment by kgnugur** [comment]
Thank you for the PR. I was what I had in my mind. It's merged now.

**Comment by verekia** [comment]
Thank you for the merge! Was the issue reopened by mistake or is there a problem? :)

**Comment by kgnugur** [comment]
Yep, we can close it now.
