### ISSUE TITLE
Thank you for making this library

### ISSUE THREAD

**Issue by verekia** [kgnugur/formik-chakra-ui#92]
I know issues are not really for this, but thank you very much for this library. It reduces boilerplate so much!

If you need help from the community to maintain it, make sure to let us know. In the Readme or with a pinned issue for instance. Since the project is pretty small, it should be relatively easy for people to jump in and help if needed.

Cheers, and thanks again.

**Comment by kgnugur** [comment]
Thank you, really. It means a lot.

My full-time job caused me to burn out, to be honest. I was wanting to help with issues but I couldn't manage to do it.

I tried to do fix some of the problems people mentioned today.  If you have suggestions, I planning to spend more time on the library.

**Comment by verekia** [comment]
Glad you're feeling better then :) No worries at all. Open source can be very taxing. I also burned out on some open source projects. It's basically giving your personal time for free, for other people, so it can feel exhausting when it starts becoming some kind of duty. Take it easy, let others help, and take as many breaks as you need!
