### ISSUE TITLE
Children should be optional in components where a label is provided

### ISSUE THREAD

**Issue by verekia** [kgnugur/formik-chakra-ui#97]
For instance: https://github.com/kgnugur/formik-chakra-ui/blob/master/src/form-checkbox/checkbox-single.tsx#L8

It seems that it should be possible to use `CheckboxSingleControl` this way:

```tsx
<CheckboxSingleControl name="hello" label="Hello" />
```

But currently it must have `children` to pass TS check:

```tsx
<CheckboxSingleControl name="hello">
  Hello
</CheckboxSingleControl>
```

**Comment by kgnugur** [comment]
Sorry for delay
